# OPENCART_PORT=8081 PHPADMIN_PORT=8888 LOCAL_IP=$(hostname -I | grep -o "^[0-9.]*") docker compose up -d

version: '3.5'
services:

  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
    ports:
      - '8888:80'
    networks:
      - selenoid

  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '3307:3306'
    networks:
      - selenoid

  opencart:
    image: bitnami/opencart:4.0.2-3-debian-12-r33
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=192.168.0.108:8080
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
    networks:
      - selenoid

  test:
    build:
      context: .
      args:
        BROWSER: ${BROWSER}
        MY_URL: ${MY_URL}
        EXECUTOR: ${EXECUTOR}
        BROWSER_VERSION: ${BROWSER_VERSION}
        THREADS: ${THREADS}
    entrypoint: >
      sh -c "./wait-for-it.sh opencart 8080 pytest
      --url=${MY_URL}
      --browser=${BROWSER}
      --executor=${EXECUTOR}
      --browser-version=${BROWSER_VERSION}
      --threads=${THREADS}
      --vnc
      --remote --alluredir=/allure-results && ls -la /allure-results"
    depends_on:
      - opencart
    networks:
      - selenoid
    environment:
      - OPENCART_HOST=opencart:8080
    volumes:
      - allure-results:/allure-results

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
  allure-results:
    driver: local

networks:
  selenoid:
    external: true